### ISSUE TITLE
Entity prototype "curved-rail"(Curved-rail) collision mask does not collide with Entity "bridge_crossing"

### ISSUE THREAD

**Issue by Protheus** [Klonan/Construction_Drones#11]
Factorio: 0.18.27
Construction_Drones: 0.6.1
cargo-ships_0.0.54
beautiful_bridge_railway_0.18.1

When loading the game with above mods, the below message pops up

![image](https://user-images.githubusercontent.com/1455178/83064565-3edafe80-a062-11ea-8b20-61df0ea254a7.png)

**Comment by Klonan** [comment]
fixed in 0.6.2
