### ISSUE TITLE
Error while running event Construction_Drones::on_ai_command_completed (ID 115)

### ISSUE THREAD

**Issue by thehe** [Klonan/Construction_Drones#12]
Error while running event Construction_Drones::on_ai_command_completed (ID 115)
__Construction_Drones__/script/construction_drone.lua:663: attempt to call global 'drone_wait' (a nil value)
stack traceback:
	__Construction_Drones__/script/construction_drone.lua:663: in function <__Construction_Drones__/script/construction_drone.lua:652>
	(...tail calls...)
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**Comment by Klonan** [comment]
Fixed in the next release
