### ISSUE TITLE
loader-1x1 loses input/output type when upgraded

### ISSUE THREAD

**Issue by mspielberg** [Klonan/Construction_Drones#15]
There is [special logic](https://github.com/Klonan/Construction_Drones/blob/master/script/construction_drone.lua#L1733) to copy over the input/output type when upgrading a `loader`, but this code doesn't check for the recently introduced `loader-1x1` type. This breaks any mod entity using this type (e.g. Miniloaders) when upgrading.

**Comment by Klonan** [comment]
Did I fix this?

**Comment by Klonan** [comment]
I guess so:
https://github.com/Klonan/Construction_Drones/commit/7bf25b9f7407e2fdf51c3708b349212dc54a90c0
