### ISSUE TITLE
Seems while deconstructing tiles.

### ISSUE THREAD

**Issue by mrbaguettefr** [Klonan/Construction_Drones#2]
![Screenshot_140](https://user-images.githubusercontent.com/11507846/54566577-8af7d100-49d1-11e9-88b5-d412665fd94c.png)

**Comment by BrotherWomba** [comment]
Can confirm this one and if needed I can provide a save game where the bug can be reproduced fairly consistently.

**Comment by Klonan** [comment]
A save game would be useful
