### ISSUE TITLE
Update 18.45 drones are not collecting large buildings

### ISSUE THREAD

**Issue by YaroslavMudrii** [Klonan/Construction_Drones#21]
Update 18.45 drones build all the drawings, but they only collect small objects (walls, tapes, manipulators) and such objects as an oil plant, an assembly machine or ventilation, he does not pick up, leave the inventory and stand looking at them.
and the sound also hangs, like they are constantly driving from the inventory to the collection object

**Comment by sthalik** [comment]
FWIW the drones are also unable to deconstruct trains. They're fine with tracks however.

**Comment by longneck** [comment]
The drones also can not place the warehouses from Factorissimo2. They shoot their laser to the center of the ghost, but they are also inside the perimeter of the ghost so the object isn't placed.

**Comment by Klonan** [comment]
I think this is fixed
