### ISSUE TITLE
Should not check for entity.valid after reviving a ghost

### ISSUE THREAD

**Issue by mspielberg** [Klonan/Construction_Drones#4]
Bulk Rail Loader utilizes a proxy entity for construction. During on_built, [a bunch of other entities are created and finally the proxy entity is destroyed](https://github.com/mspielberg/factorio-railloader/blob/06cffb566cbd297187b8dc231476c0c0840a6f13/control.lua#L190-L198). As to why, BRLs can be built in different directions, but the main entity of a BRL is a container, which cannot have a direction.

This works fine, except that Construction Drones isn't content with just checking `success` from the revive() call, but also [checks if the returned entity is non-nil](https://github.com/Klonan/Construction_Drones/blob/master/script/construction_drone.lua#L1607). Since the entity was destroyed as part of the revive event handler, nil is returned along with true.

Construction Drones is treating this as a failed attempt to build the entity, so the drone returns to the player and gives the item back, leaving the player with an extra item. It should be enough to just check `success`.

**Comment by Klonan** [comment]
Ok, should be fixed
