### ISSUE TITLE
Issues with 3rd party mods

### ISSUE THREAD

**Issue by AussieDumbAss** [Klonan/Construction_Drones#8]
![image](https://user-images.githubusercontent.com/26104461/77827031-1f594f80-715f-11ea-81f5-9cc086931d3d.png)

Not sure on whos end this is, but when replacing a Yellow belt with Red belt next to a belt balancer, game crashes with above message.

**Comment by AussieDumbAss** [comment]
Having a similar issue with https://mods.factorio.com/mod/Factorio-Tiberium

Upon placing an item that connects to another this mod crashes the save file.

Reproducable and stops occuring when manually placing the items or unloading the mod.

**Comment by AussieDumbAss** [comment]
Reproduction Steps (Belt Balancer):

Create a transport belt line
place material on belt
terminate with belt balancer
put transport belt on exits or inputs
upgrade belt to next (or previous) tier with construction drones

Reproduction Steps (Command & Factorio):

Place power
Place SRF Emitter hub (1)
Place SRF Emitter Hub (2) 2 blocks away
Wait for 5MW to enter both units

**Comment by Klonan** [comment]
It seems to me they aren't checking if the entity is valid or not

**Comment by Klonan** [comment]
I am not doing anything funny in that area, I am creating an entity in the normal way and using the normal way of sending that event to other mods:
```lua
surface.create_entity
  {
    name = prototype.name,
    position = position,
    direction = target.direction,
    fast_replace = true,
    force = target.force,
    spill = false,
    type = type or nil,
    raise_built = true
  }
```

Seems to me an issue on the other mods
